"use client";
import type { TourItineraryOutput } from "@/ai/flows/personalized-tour-itinerary";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { BookMarked, Share2 } from "lucide-react";
import { ShareButton } from "../ShareButton";

type ItineraryDisplayProps = {
  itinerary: TourItineraryOutput;
  title: string;
};

type SavedTour = {
  id: string;
  title: string;
  itinerary: TourItineraryOutput;
  savedAt: string;
};

export function ItineraryDisplay({ itinerary, title }: ItineraryDisplayProps) {
  const { toast } = useToast();

  const handleSave = () => {
    try {
      const savedTours: SavedTour[] = JSON.parse(localStorage.getItem("savedTours") || "[]");
      const newTour: SavedTour = {
        id: new Date().toISOString(),
        title: title,
        itinerary: itinerary,
        savedAt: new Date().toLocaleString(),
      };
      
      const updatedTours = [newTour, ...savedTours];
      localStorage.setItem("savedTours", JSON.stringify(updatedTours));

      toast({
        title: "Itinerary Saved!",
        description: "You can view it in 'My Tours' anytime.",
      });
    } catch (error) {
      console.error("Failed to save itinerary:", error);
      toast({
        variant: "destructive",
        title: "Save Failed",
        description: "Could not save your itinerary. Your browser might not support this feature.",
      });
    }
  };

  const shareText = `Check out my Sri Lanka trip plan from LankaGuide AI: ${itinerary.itinerary.substring(0, 150)}...`;

  return (
    <Card className="animate-in fade-in-50">
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Your Custom Itinerary: {title}</CardTitle>
        <CardDescription>Generated by LankaGuide AI just for you.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="prose prose-sm max-w-none text-foreground whitespace-pre-wrap rounded-md bg-muted p-4">
          {itinerary.itinerary}
        </div>
      </CardContent>
      <CardFooter className="flex justify-end space-x-2">
        <Button variant="outline" onClick={handleSave}>
          <BookMarked className="mr-2 h-4 w-4" />
          Save for Offline
        </Button>
        <ShareButton shareText={shareText} />
      </CardFooter>
    </Card>
  );
}
